#!/bin/sh

. /etc/openwrt_release

THERMAL_PATH="/sys/class/thermal"
cpu_temp=""

case "$DISTRIB_TARGET" in
ipq40xx/*)
	cpu_temp="$(awk '/^[0-9]+$/ { printf "%.1f°C", $1 / 1000; exit }' "$THERMAL_PATH/thermal_zone0/temp" 2>/dev/null)"
	;;
esac

if [ -n "$cpu_temp" ]; then
	printf 'CPU: %s' "$cpu_temp"
else
	printf 'No temperature info'
fi
