#!/bin/sh

MIRROR='https://mirrors.vsean.net/openwrt'
ROOT_PASSWORD_HASH='$1$immortal$qSmS/2VYmMvAclD4gWaHO0'

uci -q get system.@imm_init[0] >/dev/null || uci -q add system imm_init >/dev/null

uci -q batch <<EOF
set network.lan.ipaddr='192.168.50.1'
set system.@imm_init[0].opkg_mirror='$MIRROR'
set luci.main.mediaurlbase='/luci-static/argon'
EOF

uci -q commit network
uci -q commit system
uci -q commit luci

if [ -f /etc/opkg/distfeeds.conf ]; then
	sed -i \
		-e "s#https://downloads.immortalwrt.org#$MIRROR#g" \
		-e "s#https://mirrors.vsean.net/openwrt#$MIRROR#g" \
		/etc/opkg/distfeeds.conf
fi

if [ -f /etc/shadow ]; then
	sed -i "s#^root:[^:]*:#root:$ROOT_PASSWORD_HASH:#" /etc/shadow
fi

exit 0
